### ISSUE TITLE
Using Hotpot v1 or v1.1?

### ISSUE THREAD

**Issue by ethanjperez** [shmsw25/DecompRC#3]
I see that in the code and README you use "hotpot_train_v1.json". However, when I download the training set from the HotpotQA website, I receive "hotpot_train_v1.1.json". Is there a difference between these two versions? If so, what are the differences, and which version did you use?

**Comment by shmsw25** [comment]
Hi @ethanjperez! Thanks for your interest in our work. According to [here](https://github.com/hotpotqa/hotpot/commit/02493f6c36431f55908ab4b30394f075bbbcbe15), v1.1 is a version which excludes extremely short questions in the train set of v1. Our work has been done on v1, but I expect v1.1 will give the same or better result since its train data has a higher quality.

**Comment by ethanjperez** [comment]
Great, that's just what I needed to know - thanks!
